### ISSUE TITLE
Can I use the SentencePiece Model file?

### ISSUE THREAD

**Issue by tylike** [microsoft/Tokenizer#15]
hi!

I have an LLM model in Onnx format and a sentencepiece.model file, and I have used HuggingFace and SentencePiece in Python. Now I plan to do inference in C# + OnnxRuntime, but I haven't found a suitable version of the SentencePiece library for C#. Can I use the SentencepieceTokenizer with SentencePiece compatibility in C#?

thanks!

**Comment by shengyfu** [comment]
I believe you can use https://github.com/microsoft/BlingFire.
