### ISSUE TITLE
Example of how to pre-download the BPE rank file

### ISSUE THREAD

**Issue by KyleMit** [microsoft/Tokenizer#18]
The ReadMe states:

> In production setting, you should pre-download the BPE rank file and call TokenizerBuilder.CreateTokenizer API to avoid downloading the BPE rank file on the fly.

Can there be additional documentation / examples as to how one might go about doing that?

**Comment by shengyfu** [comment]
Yes, the locations to download the BPE rank file are defined in https://github.com/microsoft/Tokenizer/blob/44cc0d603b22483abcc71310e25b8b3746f32cd9/Tokenizer_C%23/TokenizerLib/TokenizerBuilder.cs#L107

**Comment by shengyfu** [comment]
I updated readme.md with the information.
