### ISSUE TITLE
Support for text-embedding-3-large

### ISSUE THREAD

**Issue by veedi** [microsoft/Tokenizer#47]
'text-embedding-3-large' model support for C# tokenizer.
```[tasklist]
### Tasks
```

**Comment by shengyfu** [comment]
For C# tokenizer, it has been ported into [`Microsoft.ML.Tokenizers`](https://www.nuget.org/packages/Microsoft.ML.Tokenizers). Please follow https://github.com/dotnet/machinelearning/blob/main/docs/code/microsoft-ml-tokenizers-migration-guide.md for migration guide and future support.
