### ISSUE TITLE
Error: ENOENT: no such file or directory, mkdir '/var/model'

### ISSUE THREAD

**Issue by sbernadsky** [microsoft/Tokenizer#48]
I'd like to use this package in an AWS Lambda function. However, I encounter the following error:
```
ERROR	Error creating tokenizer Error: ENOENT: no such file or directory, mkdir '/var/model'
```

This error occurs when I attempt to call createByModelName:
```
const tokenizer = await createByModelName('gpt-3.5-turbo')
```
I suspect this happens because the current code uses __dirname to create a local file (it's '/var' in Lambda), but AWS Lambda only allows writing to the /tmp folder.

Is there a way to work around this issue?

**Comment by shengyfu** [comment]
In production setting, you should pre-download the BPE rank file and call `createTokenizer` API to avoid downloading the BPE rank file on the fly. You can find the model to encoder and encoder to BPE rank file link mapping in: [tokenizerBuilder.ts](https://github.com/microsoft/Tokenizer/blob/main/tokenizer_ts/src/tokenizerBuilder.ts#L15-L55).
